### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [atgreen/cl-etcd#1]
Building with SBCL 2.1.7.62-417920f09 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 36e6fa07c069953525579115f4f143166dcd22fb

*cl-etcd* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BF8103}>: Component :CL-STR not found, required by #<SYSTEM "cl-etcd">

```

*etcd-test* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BF8103}>: Component :CL-STR not found, required by #<SYSTEM "cl-etcd">

```

[Full log here](http://report.quicklisp.org/2021-09-02/failure-report/cl-etcd.html)

**Comment by atgreen** [comment]
Whoops - I had ths as a local change and forgot to commit it.  Done now.
