### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [atgreen/cl-etcd#2]
Building with SBCL 2.1.7.62-417920f09 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id e11de3bbe271d28a14da58cb694b7d3d1e0d487f

*cl-etcd* fails to build with the following error:

```
; caught WARNING:
;   The function CDR is called with three arguments, but wants exactly one.
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BF0103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-etcd" "etcd">

```

*etcd-test* fails to build because of a failure in  _cl-etcd_.

[Full log here](http://report.quicklisp.org/2021-09-12/failure-report/cl-etcd.html)

**Comment by atgreen** [comment]
This was fixed.  Thanks.
